apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: secret #encode secret with base64 echo -n "secret" | base64
  aws_secret_access_key: secret #encode secret with base64
